insert into trayecto (id_estacion, id_tren, nombre) values (33, 84, 'Bogan, Farrell and Hermiston');
insert into trayecto (id_estacion, id_tren, nombre) values (58, 89, 'Swift, Muller and Terry');
insert into trayecto (id_estacion, id_tren, nombre) values (8, 8, 'Jast LLC');
insert into trayecto (id_estacion, id_tren, nombre) values (56, 55, 'Koelpin-Hudson');
insert into trayecto (id_estacion, id_tren, nombre) values (62, 9, 'Lueilwitz, Greenholt and McCullough');
insert into trayecto (id_estacion, id_tren, nombre) values (55, 79, 'Heller-Jacobson');
insert into trayecto (id_estacion, id_tren, nombre) values (88, 39, 'Koepp, Runte and Stoltenberg');
insert into trayecto (id_estacion, id_tren, nombre) values (98, 56, 'O''Connell, Rempel and Mosciski');
insert into trayecto (id_estacion, id_tren, nombre) values (69, 82, 'Bruen, Dickens and Glover');
insert into trayecto (id_estacion, id_tren, nombre) values (29, 69, 'Feeney, Erdman and Weimann');
insert into trayecto (id_estacion, id_tren, nombre) values (68, 84, 'Schuppe LLC');
insert into trayecto (id_estacion, id_tren, nombre) values (89, 93, 'Lebsack Group');
insert into trayecto (id_estacion, id_tren, nombre) values (101, 17, 'Mills-Rodriguez');
insert into trayecto (id_estacion, id_tren, nombre) values (7, 70, 'Kozey, MacGyver and Reinger');
insert into trayecto (id_estacion, id_tren, nombre) values (81, 37, 'Turner, Towne and Hayes');
insert into trayecto (id_estacion, id_tren, nombre) values (5, 69, 'Blick-Schumm');
insert into trayecto (id_estacion, id_tren, nombre) values (42, 72, 'Cartwright, Harvey and Kub');
insert into trayecto (id_estacion, id_tren, nombre) values (51, 99, 'Prosacco-Schamberger');
insert into trayecto (id_estacion, id_tren, nombre) values (94, 99, 'Purdy Inc');
insert into trayecto (id_estacion, id_tren, nombre) values (89, 79, 'Little, Price and Reilly');
insert into trayecto (id_estacion, id_tren, nombre) values (27, 53, 'Schroeder, Runolfsdottir and Abernathy');
insert into trayecto (id_estacion, id_tren, nombre) values (66, 16, 'Harris, Lehner and Roberts');
insert into trayecto (id_estacion, id_tren, nombre) values (52, 22, 'Hintz, Bartoletti and White');
insert into trayecto (id_estacion, id_tren, nombre) values (76, 22, 'Marquardt LLC');
insert into trayecto (id_estacion, id_tren, nombre) values (92, 56, 'Flatley and Sons');
insert into trayecto (id_estacion, id_tren, nombre) values (50, 3, 'Shanahan Group');
insert into trayecto (id_estacion, id_tren, nombre) values (13, 3, 'Berge-Goodwin');
insert into trayecto (id_estacion, id_tren, nombre) values (50, 28, 'Fahey-Dietrich');
insert into trayecto (id_estacion, id_tren, nombre) values (92, 28, 'Torp, Stracke and Douglas');
insert into trayecto (id_estacion, id_tren, nombre) values (74, 36, 'Haag, Nienow and Walter');
insert into trayecto (id_estacion, id_tren, nombre) values (55, 37, 'Lind Group');
insert into trayecto (id_estacion, id_tren, nombre) values (6, 66, 'Moen and Sons');
insert into trayecto (id_estacion, id_tren, nombre) values (81, 101, 'Brown LLC');
insert into trayecto (id_estacion, id_tren, nombre) values (102, 52, 'Bartell-Williamson');
insert into trayecto (id_estacion, id_tren, nombre) values (52, 6, 'Grimes-Stiedemann');
insert into trayecto (id_estacion, id_tren, nombre) values (91, 88, 'Doyle-Shanahan');
insert into trayecto (id_estacion, id_tren, nombre) values (37, 70, 'Erdman-Hudson');
insert into trayecto (id_estacion, id_tren, nombre) values (45, 25, 'Stark, Ernser and Zemlak');
insert into trayecto (id_estacion, id_tren, nombre) values (25, 1, 'Beatty-Nolan');
insert into trayecto (id_estacion, id_tren, nombre) values (98, 41, 'Rohan LLC');
insert into trayecto (id_estacion, id_tren, nombre) values (22, 14, 'Johns Group');
insert into trayecto (id_estacion, id_tren, nombre) values (96, 73, 'Heaney-Fisher');
insert into trayecto (id_estacion, id_tren, nombre) values (19, 70, 'Rohan Inc');
insert into trayecto (id_estacion, id_tren, nombre) values (36, 2, 'Ryan Inc');
insert into trayecto (id_estacion, id_tren, nombre) values (19, 23, 'Marquardt Group');
insert into trayecto (id_estacion, id_tren, nombre) values (93, 4, 'Roob LLC');
insert into trayecto (id_estacion, id_tren, nombre) values (29, 41, 'Braun, Smitham and Ledner');
insert into trayecto (id_estacion, id_tren, nombre) values (96, 27, 'Rohan, Ebert and Roob');
insert into trayecto (id_estacion, id_tren, nombre) values (68, 54, 'Lesch, Schuppe and Kertzmann');
insert into trayecto (id_estacion, id_tren, nombre) values (76, 53, 'Hand, Haley and Schultz');
insert into trayecto (id_estacion, id_tren, nombre) values (96, 87, 'Kuhlman, Strosin and Greenfelder');
insert into trayecto (id_estacion, id_tren, nombre) values (76, 28, 'Gottlieb Inc');
insert into trayecto (id_estacion, id_tren, nombre) values (82, 80, 'Pouros, Cummings and Dicki');
insert into trayecto (id_estacion, id_tren, nombre) values (13, 18, 'Hamill, Kunde and Bergstrom');
insert into trayecto (id_estacion, id_tren, nombre) values (77, 10, 'Wisoky-Waters');
insert into trayecto (id_estacion, id_tren, nombre) values (61, 45, 'Bosco-Lehner');
insert into trayecto (id_estacion, id_tren, nombre) values (15, 33, 'O''Conner, Legros and Purdy');
insert into trayecto (id_estacion, id_tren, nombre) values (55, 28, 'Rogahn-Bode');
insert into trayecto (id_estacion, id_tren, nombre) values (59, 65, 'Turner-Hilll');
insert into trayecto (id_estacion, id_tren, nombre) values (88, 37, 'Reynolds-Marquardt');
insert into trayecto (id_estacion, id_tren, nombre) values (79, 60, 'Cormier, Conroy and Sanford');
insert into trayecto (id_estacion, id_tren, nombre) values (40, 19, 'Krajcik-Monahan');
insert into trayecto (id_estacion, id_tren, nombre) values (54, 64, 'Blanda LLC');
insert into trayecto (id_estacion, id_tren, nombre) values (55, 1, 'Crooks LLC');
insert into trayecto (id_estacion, id_tren, nombre) values (51, 69, 'Runolfsdottir LLC');
insert into trayecto (id_estacion, id_tren, nombre) values (63, 66, 'Kovacek Group');
insert into trayecto (id_estacion, id_tren, nombre) values (41, 86, 'Ortiz, Mante and Reichel');
insert into trayecto (id_estacion, id_tren, nombre) values (70, 81, 'O''Kon-Adams');
insert into trayecto (id_estacion, id_tren, nombre) values (93, 88, 'Conroy, Bergnaum and Runte');
insert into trayecto (id_estacion, id_tren, nombre) values (37, 61, 'Wehner-Gulgowski');
insert into trayecto (id_estacion, id_tren, nombre) values (50, 35, 'Hackett-Batz');
insert into trayecto (id_estacion, id_tren, nombre) values (13, 49, 'Hintz, McDermott and Stiedemann');
insert into trayecto (id_estacion, id_tren, nombre) values (50, 75, 'Dickens and Sons');
insert into trayecto (id_estacion, id_tren, nombre) values (79, 45, 'Weimann-Christiansen');
insert into trayecto (id_estacion, id_tren, nombre) values (8, 85, 'O''Conner-Jerde');
insert into trayecto (id_estacion, id_tren, nombre) values (11, 89, 'Muller-Macejkovic');
insert into trayecto (id_estacion, id_tren, nombre) values (56, 38, 'Konopelski-Collier');
insert into trayecto (id_estacion, id_tren, nombre) values (89, 86, 'VonRueden, Gerhold and Boehm');
insert into trayecto (id_estacion, id_tren, nombre) values (48, 17, 'Gutmann, Waters and Stroman');
insert into trayecto (id_estacion, id_tren, nombre) values (35, 100, 'Bailey, Fahey and Jakubowski');
insert into trayecto (id_estacion, id_tren, nombre) values (80, 39, 'Kling Inc');
insert into trayecto (id_estacion, id_tren, nombre) values (34, 64, 'Zemlak, Connelly and Fadel');
insert into trayecto (id_estacion, id_tren, nombre) values (47, 81, 'Schimmel LLC');
insert into trayecto (id_estacion, id_tren, nombre) values (84, 5, 'Sanford, Block and Hauck');
insert into trayecto (id_estacion, id_tren, nombre) values (87, 47, 'Gaylord-Rath');
insert into trayecto (id_estacion, id_tren, nombre) values (93, 88, 'Gislason Group');
insert into trayecto (id_estacion, id_tren, nombre) values (68, 90, 'Lehner Inc');
insert into trayecto (id_estacion, id_tren, nombre) values (6, 102, 'Jacobson-Ebert');
insert into trayecto (id_estacion, id_tren, nombre) values (57, 77, 'Crist-Murazik');
insert into trayecto (id_estacion, id_tren, nombre) values (26, 51, 'Nitzsche, Shanahan and Hilpert');
insert into trayecto (id_estacion, id_tren, nombre) values (6, 26, 'Parisian, Simonis and Reinger');
insert into trayecto (id_estacion, id_tren, nombre) values (31, 53, 'VonRueden, Willms and Feil');
insert into trayecto (id_estacion, id_tren, nombre) values (36, 54, 'Bergstrom LLC');
insert into trayecto (id_estacion, id_tren, nombre) values (76, 96, 'Hagenes, Dietrich and Hirthe');
insert into trayecto (id_estacion, id_tren, nombre) values (6, 84, 'Ferry LLC');
insert into trayecto (id_estacion, id_tren, nombre) values (58, 38, 'Metz and Sons');
insert into trayecto (id_estacion, id_tren, nombre) values (34, 43, 'Cummings, Gaylord and Fadel');
insert into trayecto (id_estacion, id_tren, nombre) values (21, 24, 'Wisoky-Stracke');
insert into trayecto (id_estacion, id_tren, nombre) values (90, 4, 'Cartwright, Harris and Kuvalis');
insert into trayecto (id_estacion, id_tren, nombre) values (5, 44, 'Hansen-Schimmel');
